### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by edwinbalani** [ocf/kubernetes#36]
Is there/should there be an OSS licence for this repo?

**Comment by ethanhs** [comment]
We dual license GPL/Apache 2.0, so we should add that here.

**Comment by nikhiljha** [comment]
I'm not sure if having a license really makes sense, since all of this is basically just configuration files. `transpire` is LGPL at the moment but we should probably relicense to be more permissive (while there are only three contributors still).

**Comment by edwinbalani** [comment]
I originally opened this impulsively, but I don't have much of a stake or opinion here.

I'm going to close the issue, but if it comes up again then it can (I think) be reopened by someone else, or a new one made.
