### ISSUE TITLE
Evaluate + Deploy an Ingress Solution

### ISSUE THREAD

**Issue by nikhiljha** [ocf/kubernetes#4]
We need some kind of Ingress provider for the cluster.

Traefik is nice but...
- it's slow compared to the envoy-based alternatives
- pretty basic features (generating TLS certs in HA mode) are locked behind a paywall

Find the nicest ingress solution and deploy it to the cluster.

**Comment by dkess** [comment]
what was wrong with nginx

**Comment by nikhiljha** [comment]
nginx is okay too, I'm pretty sure it also supports raw TCP/UDP

...but the new cluster has nothing, so if something better exists we should use it

**Comment by nikhiljha** [comment]
Resolution: Traefik is a massive pain. I installed Contour (https://github.com/ocf/kubernetes/commit/3781e531f888c95dccb87032ffa25aceca9d37d2) and it's been smooth sailing (also supposedly Contour is more performant, which is nice).
