### ISSUE TITLE
Ceph

### ISSUE THREAD

**Issue by nikhiljha** [ocf/kubernetes#8]
We need storage! HDDs go brrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by ja5087** [comment]
Seems like the current direction we're heading in is to use Rook to manage Ceph for us? 

On an unrelated note, while we still have non-k8s uses it may be useful to configure it to expose it outside the cluster too as per https://www.adaltas.com/en/2020/04/16/expose-ceph-from-rook-kubernetes/

**Comment by nikhiljha** [comment]
Progress here: https://github.com/ocf/kubernetes/commit/7488ca889f4c734e817d3818334ed27c8c6cc171

Currently the Ceph cluster is running, but it's not accessible from inside Kubernetes.

**Comment by nikhiljha** [comment]
closed in https://github.com/ocf/kubernetes/commit/254132901edaed024386ada3d5ca7a09df36f6f8
